export const skills = [
  'Escribir',
  'Liderazgo',
  'Etica',
  'Comunicación',
  'Iniciativa',
  'Escuchar',
  'Hablar',
  'Negociar',
  'Adminstracion de Tiempo',
  'Adminstracion de Dinero',
  'Reparar Equipo',
  'Instalacion de Equipo',
  'Plomeria',
  'Mecanica',
  'Creatividad',
  'Diseño',
  'Programar',
  'Pintar',
  'Dibujar',
  'Carpintería',
];
